export const TYPE_LIST = [
  { name: 'ノーマル', class: 'normal', },
  { name: 'かくとう', class: 'fighting', },
  { name: 'ひこう', class: 'flying', },
  { name: 'どく', class: 'poison', },
  { name: 'じめん', class: 'ground', },
  { name: 'いわ', class: 'rock', },
  { name: 'むし', class: 'bug', },
  { name: 'ゴースト', class: 'ghost', },
  { name: 'はがね', class: 'steel', },
  { name: 'ほのお', class: 'fire', },
  { name: 'みず', class: 'water', },
  { name: 'くさ', class: 'grass', },
  { name: 'でんき', class: 'electric', },
  { name: 'エスパー', class: 'psychic', },
  { name: 'こおり', class: 'ice', },
  { name: 'ドラゴン', class: 'dragon', },
  { name: 'あく', class: 'dark', },
  { name: 'フェアリー', class: 'fairy', },
];